[package]
name = "galimono"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1"
ogl33 = { version = "0.2.0", features = ["debug_error_checks"] }
beryllium = "0.2.0-alpha.4"
image = "0.25.2"
ultraviolet = "0.9.2"

[dev-dependencies]
